/**
 * Sample Templates for quick start
 */

export const SAMPLE_TEMPLATES = [
  {
    id: 'welcome',
    name: 'Welcome Email',
    description: 'Onboard new users with a warm welcome',
    thumbnail: '👋',
    sampleData: {
      'user.name': 'Sarah Johnson',
      'user.email': 'sarah@example.com',
      'company.name': 'TechStart Inc.',
      'company.address': '123 Innovation Drive, San Francisco, CA 94102',
      'action.url': 'https://app.techstart.com/get-started',
      'unsubscribe.url': 'https://techstart.com/unsubscribe',
    },
    blocks: [
      {
        id: 'header-1',
        type: 'header',
        content: {
          text: 'Welcome to {{company.name}}!',
          level: 'h1',
          align: 'center',
          color: '#333333',
          backgroundColor: '#ffffff',
          padding: 40,
        },
      },
      {
        id: 'text-1',
        type: 'text',
        content: {
          text: "Hi {{user.name}},\n\nWe're thrilled to have you join our community! Your account has been successfully created and you're all set to get started.",
          align: 'left',
          color: '#666666',
          fontSize: 16,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'button-1',
        type: 'button',
        content: {
          text: 'Get Started',
          url: '{{action.url}}',
          align: 'center',
          buttonColor: '#22c55e',
          textColor: '#ffffff',
          borderRadius: 6,
          padding: 30,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'text-2',
        type: 'text',
        content: {
          text: "If you have any questions, feel free to reply to this email or visit our help center. We're here to help!",
          align: 'left',
          color: '#666666',
          fontSize: 14,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'divider-1',
        type: 'divider',
        content: {
          color: '#eeeeee',
          thickness: 1,
          style: 'solid',
          width: '100%',
          padding: 20,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'footer-1',
        type: 'footer',
        content: {
          text: '© 2024 {{company.name}}. All rights reserved.',
          address: '{{company.address}}',
          unsubscribeText: 'Unsubscribe',
          unsubscribeUrl: '{{unsubscribe.url}}',
          align: 'center',
          color: '#999999',
          fontSize: 12,
          backgroundColor: '#f8f8f8',
          padding: 30,
        },
      },
    ],
    settings: {
      backgroundColor: '#f4f4f4',
      contentWidth: 600,
      fontFamily: 'Arial, sans-serif',
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    description: 'Share updates and news with subscribers',
    thumbnail: '📰',
    sampleData: {
      'user.name': 'Alex Chen',
      'company.name': 'Tech Weekly',
      'company.address': '100 Tech Park, Austin, TX 78701',
      'website.url': 'https://techweekly.com',
      'newsletter.title': 'This Week in Tech - December Edition',
      'article.summary': 'Discover the top 10 AI trends that will shape 2025, from autonomous agents to multimodal models.',
      'article.url': 'https://techweekly.com/ai-trends-2025',
      'social.facebook': 'https://facebook.com/techweekly',
      'social.twitter': 'https://twitter.com/techweekly',
      'social.instagram': 'https://instagram.com/techweekly',
      'social.linkedin': 'https://linkedin.com/company/techweekly',
      'unsubscribe.url': 'https://techweekly.com/unsubscribe',
    },
    blocks: [
      {
        id: 'image-1',
        type: 'image',
        content: {
          src: 'https://via.placeholder.com/600x150/4F46E5/ffffff?text={{company.name}}',
          alt: 'Company Logo',
          width: '100%',
          align: 'center',
          link: '{{website.url}}',
          backgroundColor: '#4F46E5',
          padding: 0,
        },
      },
      {
        id: 'header-1',
        type: 'header',
        content: {
          text: '{{newsletter.title}}',
          level: 'h1',
          align: 'center',
          color: '#333333',
          backgroundColor: '#ffffff',
          padding: 30,
        },
      },
      {
        id: 'text-1',
        type: 'text',
        content: {
          text: "Hello {{user.name}},\n\nHere's what's new this week! We've got exciting updates and news to share with you.",
          align: 'left',
          color: '#666666',
          fontSize: 16,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'divider-1',
        type: 'divider',
        content: {
          color: '#eeeeee',
          thickness: 1,
          style: 'solid',
          width: '80%',
          padding: 10,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'header-2',
        type: 'header',
        content: {
          text: '📌 Featured Article',
          level: 'h2',
          align: 'left',
          color: '#333333',
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'text-2',
        type: 'text',
        content: {
          text: '{{article.summary}}\n\nThis is a brief description of our featured article that highlights the key points and encourages readers to learn more.',
          align: 'left',
          color: '#666666',
          fontSize: 15,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'button-1',
        type: 'button',
        content: {
          text: 'Read More →',
          url: '{{article.url}}',
          align: 'left',
          buttonColor: '#4F46E5',
          textColor: '#ffffff',
          borderRadius: 6,
          padding: 20,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'spacer-1',
        type: 'spacer',
        content: {
          height: 20,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'social-1',
        type: 'social',
        content: {
          align: 'center',
          facebook: '{{social.facebook}}',
          twitter: '{{social.twitter}}',
          instagram: '{{social.instagram}}',
          linkedin: '{{social.linkedin}}',
          iconSize: 32,
          padding: 20,
          backgroundColor: '#f8f8f8',
        },
      },
      {
        id: 'footer-1',
        type: 'footer',
        content: {
          text: '© 2024 {{company.name}}',
          address: '{{company.address}}',
          unsubscribeText: 'Unsubscribe from this list',
          unsubscribeUrl: '{{unsubscribe.url}}',
          align: 'center',
          color: '#999999',
          fontSize: 12,
          backgroundColor: '#f8f8f8',
          padding: 20,
        },
      },
    ],
    settings: {
      backgroundColor: '#f0f0f0',
      contentWidth: 600,
      fontFamily: "'Helvetica Neue', Helvetica, sans-serif",
    },
  },
  {
    id: 'order-confirmation',
    name: 'Order Confirmation',
    description: 'Confirm customer orders with details',
    thumbnail: '🛒',
    sampleData: {
      'user.name': 'Michael Roberts',
      'company.name': 'ShopEasy',
      'order.number': 'ORD-2024-78542',
      'order.date': 'December 8, 2024',
      'order.total': '$149.99',
      'order.tracking_url': 'https://shopeasy.com/track/78542',
      'shipping.address': '789 Oak Street, Apt 4B',
      'shipping.city': 'Brooklyn',
      'shipping.zip': 'NY 11201',
      'support.email': 'support@shopeasy.com',
      'preferences.url': 'https://shopeasy.com/preferences',
    },
    blocks: [
      {
        id: 'header-1',
        type: 'header',
        content: {
          text: '✓ Order Confirmed!',
          level: 'h1',
          align: 'center',
          color: '#22c55e',
          backgroundColor: '#f0fdf4',
          padding: 40,
        },
      },
      {
        id: 'text-1',
        type: 'text',
        content: {
          text: 'Hi {{user.name}},\n\nThank you for your order! We\'ve received your order and it\'s being processed.',
          align: 'left',
          color: '#666666',
          fontSize: 16,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'header-2',
        type: 'header',
        content: {
          text: 'Order Details',
          level: 'h2',
          align: 'left',
          color: '#333333',
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'text-2',
        type: 'text',
        content: {
          text: 'Order Number: {{order.number}}\nOrder Date: {{order.date}}\nTotal: {{order.total}}',
          align: 'left',
          color: '#333333',
          fontSize: 14,
          lineHeight: 1.8,
          backgroundColor: '#f9fafb',
          padding: 20,
        },
      },
      {
        id: 'divider-1',
        type: 'divider',
        content: {
          color: '#e5e7eb',
          thickness: 1,
          style: 'solid',
          width: '100%',
          padding: 20,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'text-3',
        type: 'text',
        content: {
          text: 'Shipping Address:\n{{shipping.address}}\n{{shipping.city}}, {{shipping.zip}}',
          align: 'left',
          color: '#666666',
          fontSize: 14,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'button-1',
        type: 'button',
        content: {
          text: 'Track Your Order',
          url: '{{order.tracking_url}}',
          align: 'center',
          buttonColor: '#3b82f6',
          textColor: '#ffffff',
          borderRadius: 6,
          padding: 30,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'footer-1',
        type: 'footer',
        content: {
          text: '© 2024 {{company.name}}',
          address: 'Questions? Contact us at {{support.email}}',
          unsubscribeText: 'Email Preferences',
          unsubscribeUrl: '{{preferences.url}}',
          align: 'center',
          color: '#999999',
          fontSize: 12,
          backgroundColor: '#f8f8f8',
          padding: 30,
        },
      },
    ],
    settings: {
      backgroundColor: '#f4f4f4',
      contentWidth: 600,
      fontFamily: 'Arial, sans-serif',
    },
  },
  {
    id: 'password-reset',
    name: 'Password Reset',
    description: 'Help users reset their password',
    thumbnail: '🔐',
    sampleData: {
      'user.name': 'Emily Watson',
      'user.email': 'emily@example.com',
      'company.name': 'SecureApp',
      'reset.url': 'https://secureapp.com/reset?token=abc123xyz789',
      'expiry.hours': '24',
    },
    blocks: [
      {
        id: 'header-1',
        type: 'header',
        content: {
          text: 'Reset Your Password',
          level: 'h1',
          align: 'center',
          color: '#333333',
          backgroundColor: '#ffffff',
          padding: 40,
        },
      },
      {
        id: 'text-1',
        type: 'text',
        content: {
          text: "Hi {{user.name}},\n\nWe received a request to reset your password. Click the button below to create a new password. This link will expire in {{expiry.hours}} hours.",
          align: 'left',
          color: '#666666',
          fontSize: 16,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'button-1',
        type: 'button',
        content: {
          text: 'Reset Password',
          url: '{{reset.url}}',
          align: 'center',
          buttonColor: '#ef4444',
          textColor: '#ffffff',
          borderRadius: 6,
          padding: 30,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'text-2',
        type: 'text',
        content: {
          text: "If you didn't request a password reset, you can safely ignore this email. Your password will remain unchanged.",
          align: 'left',
          color: '#999999',
          fontSize: 14,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'divider-1',
        type: 'divider',
        content: {
          color: '#eeeeee',
          thickness: 1,
          style: 'solid',
          width: '100%',
          padding: 20,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'text-3',
        type: 'text',
        content: {
          text: "If the button doesn't work, copy and paste this link:\n{{reset.url}}",
          align: 'left',
          color: '#999999',
          fontSize: 12,
          lineHeight: 1.6,
          backgroundColor: '#f9fafb',
          padding: 20,
        },
      },
      {
        id: 'footer-1',
        type: 'footer',
        content: {
          text: '© 2024 {{company.name}}',
          address: 'This is an automated message. Please do not reply.',
          unsubscribeText: '',
          unsubscribeUrl: '',
          align: 'center',
          color: '#999999',
          fontSize: 12,
          backgroundColor: '#f8f8f8',
          padding: 20,
        },
      },
    ],
    settings: {
      backgroundColor: '#f4f4f4',
      contentWidth: 500,
      fontFamily: 'Arial, sans-serif',
    },
  },
  {
    id: 'promotional',
    name: 'Promotional Offer',
    description: 'Announce sales and special offers',
    thumbnail: '🎉',
    sampleData: {
      'user.name': 'Jessica Miller',
      'company.name': 'FashionHub',
      'company.address': '456 Style Ave, New York, NY 10001',
      'promo.title': 'HOLIDAY MEGA SALE!',
      'promo.discount': '50% OFF',
      'promo.code': 'HOLIDAY50',
      'promo.url': 'https://fashionhub.com/sale',
      'promo.expiry': 'December 31, 2024',
      'unsubscribe.url': 'https://fashionhub.com/unsubscribe',
    },
    blocks: [
      {
        id: 'image-1',
        type: 'image',
        content: {
          src: 'https://via.placeholder.com/600x250/ec4899/ffffff?text=SALE',
          alt: 'Sale Banner',
          width: '100%',
          align: 'center',
          link: '{{promo.url}}',
          backgroundColor: '#ec4899',
          padding: 0,
        },
      },
      {
        id: 'header-1',
        type: 'header',
        content: {
          text: '🔥 {{promo.title}}',
          level: 'h1',
          align: 'center',
          color: '#ec4899',
          backgroundColor: '#ffffff',
          padding: 30,
        },
      },
      {
        id: 'text-1',
        type: 'text',
        content: {
          text: "Hey {{user.name}}!\n\nDon't miss out on our biggest sale of the year! Get {{promo.discount}} off everything in store.",
          align: 'center',
          color: '#666666',
          fontSize: 18,
          lineHeight: 1.6,
          backgroundColor: '#ffffff',
          padding: 20,
        },
      },
      {
        id: 'header-2',
        type: 'header',
        content: {
          text: 'Use Code: {{promo.code}}',
          level: 'h2',
          align: 'center',
          color: '#333333',
          backgroundColor: '#fef3c7',
          padding: 20,
        },
      },
      {
        id: 'text-2',
        type: 'text',
        content: {
          text: 'Offer valid until {{promo.expiry}}. Terms and conditions apply.',
          align: 'center',
          color: '#999999',
          fontSize: 14,
          lineHeight: 1.4,
          backgroundColor: '#ffffff',
          padding: 15,
        },
      },
      {
        id: 'button-1',
        type: 'button',
        content: {
          text: 'Shop Now →',
          url: '{{promo.url}}',
          align: 'center',
          buttonColor: '#ec4899',
          textColor: '#ffffff',
          borderRadius: 30,
          padding: 30,
          backgroundColor: '#ffffff',
        },
      },
      {
        id: 'footer-1',
        type: 'footer',
        content: {
          text: '© 2024 {{company.name}}',
          address: '{{company.address}}',
          unsubscribeText: 'Unsubscribe',
          unsubscribeUrl: '{{unsubscribe.url}}',
          align: 'center',
          color: '#999999',
          fontSize: 12,
          backgroundColor: '#f8f8f8',
          padding: 20,
        },
      },
    ],
    settings: {
      backgroundColor: '#fdf2f8',
      contentWidth: 600,
      fontFamily: 'Arial, sans-serif',
    },
  },
  {
    id: 'blank',
    name: 'Blank Template',
    description: 'Start from scratch',
    thumbnail: '📄',
    sampleData: {
      'user.name': 'John Doe',
      'user.email': 'john@example.com',
      'company.name': 'Your Company',
      'company.address': '123 Main Street, City, State 12345',
      'website.url': 'https://example.com',
      'unsubscribe.url': 'https://example.com/unsubscribe',
    },
    blocks: [],
    settings: {
      backgroundColor: '#f4f4f4',
      contentWidth: 600,
      fontFamily: 'Arial, sans-serif',
    },
  },
];

/**
 * Sample data for placeholder preview
 */
export const SAMPLE_DATA_SETS = [
  {
    id: 'default',
    name: 'Default Sample Data',
    description: 'Generic sample values',
    data: {
      'user.name': 'John Doe',
      'user.email': 'john@example.com',
      'user.firstName': 'John',
      'user.lastName': 'Doe',
      'company.name': 'Acme Corporation',
      'company.address': '123 Main Street, San Francisco, CA 94102',
      'action.url': 'https://example.com/action',
      'website.url': 'https://example.com',
      'unsubscribe.url': 'https://example.com/unsubscribe',
      'preferences.url': 'https://example.com/preferences',
      'support.email': 'support@example.com',
    },
  },
  {
    id: 'ecommerce',
    name: 'E-commerce Data',
    description: 'Order and shopping data',
    data: {
      'user.name': 'Sarah Johnson',
      'user.email': 'sarah@example.com',
      'company.name': 'ShopEasy',
      'company.address': '456 Commerce Ave, New York, NY 10001',
      'order.number': 'ORD-2024-78542',
      'order.date': 'December 8, 2024',
      'order.total': '$149.99',
      'order.tracking_url': 'https://example.com/track/78542',
      'shipping.address': '789 Oak Street, Apt 4B',
      'shipping.city': 'Brooklyn',
      'shipping.zip': 'NY 11201',
      'promo.code': 'SAVE20',
      'promo.discount': '20%',
      'promo.title': 'Holiday Sale!',
      'promo.url': 'https://example.com/sale',
      'promo.expiry': 'December 31, 2024',
      'unsubscribe.url': 'https://example.com/unsubscribe',
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter Data',
    description: 'Content and articles',
    data: {
      'user.name': 'Alex Chen',
      'company.name': 'Tech Weekly',
      'company.address': '100 Tech Park, Austin, TX 78701',
      'newsletter.title': 'This Week in Tech',
      'article.title': '10 AI Trends for 2025',
      'article.summary': 'Discover the top artificial intelligence trends that will shape the technology landscape in the coming year.',
      'article.url': 'https://example.com/article/ai-trends',
      'website.url': 'https://example.com',
      'social.facebook': 'https://facebook.com/techweekly',
      'social.twitter': 'https://twitter.com/techweekly',
      'social.instagram': 'https://instagram.com/techweekly',
      'social.linkedin': 'https://linkedin.com/company/techweekly',
      'unsubscribe.url': 'https://example.com/unsubscribe',
    },
  },
  {
    id: 'security',
    name: 'Security/Auth Data',
    description: 'Password reset and verification',
    data: {
      'user.name': 'Mike Wilson',
      'user.email': 'mike@example.com',
      'company.name': 'SecureApp',
      'reset.url': 'https://example.com/reset?token=abc123xyz',
      'verify.url': 'https://example.com/verify?token=xyz789abc',
      'expiry.hours': '24',
      'ip.address': '192.168.1.100',
      'device.name': 'Chrome on Windows',
      'login.time': 'December 8, 2024 at 3:45 PM',
      'login.location': 'San Francisco, CA',
    },
  },
];

/**
 * Get sample data by ID
 */
export function getSampleDataById(id) {
  return SAMPLE_DATA_SETS.find((s) => s.id === id)?.data || SAMPLE_DATA_SETS[0].data;
}

/**
 * Get template by ID
 */
export function getTemplateById(id) {
  return SAMPLE_TEMPLATES.find((t) => t.id === id);
}

